#!/bin/bash

echo "------------------------------------------------------"
echo "  Script de instalación de mi configuración de BSPWM  "
echo "------------------------------------------------------"
echo ""

echo "Crear directorio ~/.config"
mkdir -p ~/.config
echo ""
echo "Creando los enlaces simbolicos"
echo "------------------------------------------------------"
dir=$pwd

ln -s $dir/.config/bspwm ~/.config/bspwm
echo "Archivo de configuración de BSPWM instalado"

ln -s $dir/.config/sxhkd ~/.config/sxhkd
echo "Archivo de configuración de SXHKD instalado"

ln -s $dir/.config/picom ~/.config/picom
echo "Archivo de configuración de PICOM instalado"

ln -s $dir/.config/polybar ~/.config/polybar
echo "Archivos de configuración de POLYBAR instalados"

ln -s $dir/.config/dunst ~/.config/dunst
echo "Archivo de configuración de DUNST instalado"

ln -s $dir/.config/termite ~/.config/termite
echo "Archivo de configuración de TERMITE instalado"

ln -s $dir/.config/powerlevel10k ~/.config/powerlevel10k
echo "Archivo de configuración de BSPWM instalado"

ln -s $dir/.config/gtk-3.0 ~/.config/gtk-3.0
echo "Archivo de configuración de GTK-3-0 instalado"

ln -s $dir/.config/redshift ~/.config/redshift
echo "Archivo de configuración de REDSHIFT instalado"

ln -s $dir/.config/rofi ~/.config/rofi
echo "Archivo de configuración de ROFI instalado"

ln -s $dir/.config/scripts ~/.config/scripts
echo "Archivo de configuración de BSPWM instalado"

ln -s $dir/.config/spicetify ~/.config/spicetify
echo "Archivo de configuración de SPICETIFY instalado"

ln -s $dir/.config/streamlink ~/.config/streamlink
echo "Archivo de configuración de STREAMLINKS instalado"

ln -s $dir/.config/wallpapers ~/.config/wallpapers
echo "Archivo de configuración de WALLPAPERS instalado"

ln -s $dir/.config/Code - OSS ~/.config/Code - OSS
echo "Archivo de configuración de VSCODE instalado"

ln -s $dir/.config/ranger ~/.config/ranger
echo "Archivo de configuración de BSPWM instalado"

ln -s $dir/.mpd ~/.mpd
echo "Archivo de configuración de MPD instalado"

ln -s $dir/.ncmpcpp ~/.ncmpcpp
echo "Archivo de configuración de NCMPCPP instalado"

ln -s $dir/.themes ~/.themes
echo "Archivo de configuración de THEMES instalado"

ln -s $dir/.Xresources ~/.Xresources
echo "Archivo de configuración de Xresources instalado"

ln -s $dir/.gtkrc-2.0 ~/.gtkrc-2.0
echo "Archivo de configuración de GTK-2.0 instalado"

ln -s $dir/.p10k.zsh ~/.p10k.zsh
echo "Archivo de configuración de P10k.ZSH instalado"

ln -s $dir/.vimrc ~/.vimrc
echo "Archivo de configuración de VIM instalado"

ln -s $dir/.xinitrc ~/.xinitrc
echo "Archivo de configuración de XINIT instalado"

ln -s $dir/.zshrc ~/.zshrc
echo "Archivo de configuración de ZSH instalado"


echo "------------------------------------------------------------"
echo "  Finalización de instalación de mi configuración de BSPWM  "
echo "------------------------------------------------------------"
