[Variables]
Main_FG =DEDEDE
Secondary_FG =DEDEDE
Main_BG =1F2022
Sidebar_And_Player_BG =1F2022
Cover_Overlay_And_Shadow =4F5154
Indicator_FG_And_Button_BG =727272
Pressing_FG =616566
Slider_BG =3F3C45
Sidebar_Indicator_And_Hover_Button_BG =F7FAFC
Scrollbar_FG_And_Selected_Row_BG =151517
Pressing_Button_FG =DEDEDE
Pressing_Button_BG =383145
Selected_Button =1C1B1B
Miscellaneous_BG =121112
Miscellaneous_Hover_BG =383145
Preserve_1 =FFFFFF
