#!/bin/sh

quality=""

if [ -z "$2" ]; then
    quality="best"
else
    quality=$2
fi

streamlink "https://twitch.tv/"miree_music $quality "${@:3}" &
midori --app="http://www.twitch.tv/"miree_music"/chat?popout=" &
